### ISSUE TITLE
CPM branch reference

### ISSUE THREAD

**Issue by hmoenck** [BioroboticsLab/bb_imageanalysis#1]
The cmake file https://github.com/BioroboticsLab/bb_imageanalysis/blob/3f64bf3c5e81f3ec0cdaee54611d6f20907b27ef/CMakeLists.txt#L59 references to the CPM branch. The branch is to be removed as discussed in BioroboticsLab/pipeline/issues/9

**Comment by nebw** [comment]
Fixed
